### ISSUE TITLE
Default installs to /bin instead of /usr/bin

### ISSUE THREAD

**Issue by cddepppp256** [cubosphere/cubosphere-code#14]
The default build installs to `/bin` instead of `/usr/bin`, witch causes a failure to install.

**Comment by v1993** [comment]
It doesn't actally cause failure, but still incorrect.

**Comment by v1993** [comment]
Seems not so important actually, check out https://stackoverflow.com/questions/53989278/wrong-cmake-install-dirs for futher info.

**Comment by v1993** [comment]
First bug fixed by me in this year :1st_place_medal:
