### ISSUE TITLE
[BUG] Fix compilation on GCC

### ISSUE THREAD

**Issue by qwertychouskie** [cubosphere/cubosphere-code#30]
This is blocking me making a Windows build.

**Comment by v1993** [comment]
This is a bug in GCC (seriously). Try [clang](https://releases.llvm.org/download.html) which work on windows too.

**Comment by v1993** [comment]
@qwertychouskie Also please avoid pseudo-lables in headers (`[BUG]`).

**Comment by qwertychouskie** [comment]
@v1993 

1. The pseudo-label is auto-added by your issue template :)
2. I need GCC support for cross-compilation.  And yes, I'm working on cross-compilation first, I will go insane if I have to spend hours upon hours in Windows, I'll test compiling directly on Windows once I have the other issues worked out. :)

The good news is that adding `-fpermissive` may fix it, testing now.

**Comment by v1993** [comment]
@qwertychouskie

1. Oh man, sorry :)
2. Clang can cross-compile too! You may want to take a look at https://github.com/tpoechtrager/wclang (didn't tested myself).
