### ISSUE TITLE
[TODO] [GCC] Use standard struct definitions

### ISSUE THREAD

**Issue by qwertychouskie** [cubosphere/cubosphere-code#33]
TODO for myself: I need to change all structs like:
```
using TraceResult = struct {
	int hit;
	float dist;
	int block;
	int side;
};
```
to:
```
struct TraceResult {
	int hit;
	float dist;
	int block;
	int side;
};
```

Not sure why these were all defined in this way, but at least the given example freaks out GCC.  @v1993 Any idea why these are all defined this way?

**Comment by v1993** [comment]
They originally were typedefed, but I replaced it with `using` for better readablity. As it turned out, `using` is not required too.

But it is really a bug in GCC.

**Comment by qwertychouskie** [comment]
Fix in https://github.com/cubosphere/cubosphere-code/commit/dad49a0b6a19d5fa061099781912d486e7297803.
