### ISSUE TITLE
Repo is unclonable

### ISSUE THREAD

**Issue by v1993** [cubosphere/cubosphere-code#34]
Dear @qwertychouskie, this project use CircleCI for automated builds. It have failed on your last commit.

Click on `build: failing` sign on main repo page and write results to me. While commit looks innocent enough by itself, you should learn a bit about that CI (check do you have access to it, setup notifications).

Please report results here.

**Comment by qwertychouskie** [comment]
For some reason, it failed grabbing the data submodule.  Will investigate later.

**Comment by v1993** [comment]
Try cloning repo: you'll fail at submodule download too! That's critical!

**Comment by qwertychouskie** [comment]
Fixed in https://github.com/cubosphere/cubosphere-code/commit/ae85797e5a6831d19b3213643000cdd79b1df84c, see https://stackoverflow.com/questions/45678862/git-submodule-update-vs-git-submodule-sync for details.
