### ISSUE TITLE
Can't view messages

### ISSUE THREAD

**Issue by Wuzzy2** [cubosphere/cubosphere-code#40]
**Describe the bug**
It is not possible to view the tutorial messages (the little speech bubbles). I tried pressing all the keys, tried reconfiguring the keys, tried keyboard and joypad, tried the Special key and everything else. Nothing works.

**To Reproduce**
1. Start level 1 Egypt
2. Try to view any messages
3. Press all the keys including the Special key, fail every time

**Expected behavior**
Message opens.

**Reference**
In the original Cubosphere Beta 0.3a, there was a little overlay when I was at a message block, saying I can press the Special key to open the message. When I pressed this key, the message opened.

**Version**
339793922be62ddd95652bc34855043096acb41d

**Comment by v1993** [comment]
Can't reproduce on last commit made by me, will try git master soon…

**Comment by qwertychouskie** [comment]
I also can not reproduce.  What OS/compiler version/etc.?

**Comment by Wuzzy2** [comment]
Linux and GCC 8.3.0.

**Comment by qwertychouskie** [comment]
@Wuzzy2 What distro/distro version?  Are you compiling Cubosphere yourself or using a package from http://cubosphere.vallua.ru/artifacts/?  Please pull/update to the latest commit, run Cubosphere, reproduce the problem (the key should be Enter), close Cubosphere, and paste the contents of `~/.cubosphere/stdout.log`.

**Comment by v1993** [comment]
If you tried old cubosphere, try removing `~/.cubosphere/config.cdef`. Old buttons config is incompatible with SDL2 update.

**Comment by v1993** [comment]
BTW, artifacts always have fresh git master build and can be used safely.

**Comment by Wuzzy2** [comment]
OK, this fixed it.
