### ISSUE TITLE
Dead link?

### ISSUE THREAD

**Issue by Achaean** [cubosphere/cubosphere-code#50]
Tried going to  http://cubosphere.vallua.ru/artifacts, only to receive an error message (SSL_ERROR_NO_CYPHER_OVERLAP).
Is it dead?

**Comment by v1993** [comment]
No it is not. Also, link works for me. Looking at error message, it's because I don't have SSL encryption in use. Why? Because of my "dear" hosting provider not collaborating with Let's encrypt and alike while having prices for SSL certification that exceed hosing costs.
