### ISSUE TITLE
READ VERY IMPORTANT

### ISSUE THREAD

**Issue by SusDTSteve** [cubosphere/cubosphere-code#52]
After having a good look, I see that this project is for Linux only. Unless there is some secret windows build I don't know about, create one. I have have some glitches to test E.G. using an elevator to clip through blocks or getting 2 balls in an exit at the same time.

**Comment by qwertychouskie** [comment]
Currently there's no Windows build of this code as it just crashes on launch.  If you need a Windows build, try https://sourceforge.net/projects/cubosphere/ (it's a bit old when it comes to code architecture, but still should work just fine.)

That being said, if you have any experience with CPP/Lua, help is appreciated!  (I have a job now, so I have very little free time to work on this anymore.)

**Comment by SusDTSteve** [comment]
i guess i could try to find the problem of where it crashes, otherwise thank you.

**Comment by SusDTSteve** [comment]
if you didnt get what i meant, i wanted the windows build that you mentioned 2 days ago.
