### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by cddepppp256** [cubosphere/cubosphere-code#6]
Error:

```
In file included from /media/user/A8847AB1847A819C/Source/cubosphere-code/src/cuboactors.hpp:19:0,
                 from /media/user/A8847AB1847A819C/Source/cubosphere-code/src/cuboactors.cpp:15:
/media/user/A8847AB1847A819C/Source/cubosphere-code/src/cubolevels.hpp: At global scope:
/media/user/A8847AB1847A819C/Source/cubosphere-code/src/cubolevels.hpp:125:15: error: ‘TraceResult CuboLevel::TraceLine(Vector3d, Vector3d, int)’, declared using unnamed type, is used but never defined [-fpermissive]
   TraceResult TraceLine(Vector3d start,Vector3d dir, int onlyblocking=0);
               ^~~~~~~~~
In file included from /media/user/A8847AB1847A819C/Source/cubosphere-code/src/cuboactors.hpp:19:0,
                 from /media/user/A8847AB1847A819C/Source/cubosphere-code/src/cuboactors.cpp:15:
```

**Comment by v1993** [comment]
Are you still unable to compile?

**Comment by v1993** [comment]
```
[19:40:02]<vyo20031> Btw https://github.com/cubosphere/cubosphere-code/issues/6
[19:40:10]<vyo20031> Can I close it?
[19:40:45]<cddepppp256> yes
[19:40:58]<cddepppp256> Think it is something wrong on my end
```

**Comment by v1993** [comment]
I think that he tried to use GCC, which have a bug.

**Comment by qwertychouskie** [comment]
`-fpermissive` allowed compilation for me, but the linker always failed until I changed the definition of TraceResult to this:
```
struct TraceResult {
	int hit;
	float dist;
	int block;
	int side;
};
```
Not sure why it was defined as it was before, but having it this way seems to make GCC happy with no other issues caused by it as far as I can tell.  Fix will come with Windows compilation PR once I figure out why the Windows binary immediately exits on launch (seemingly before hitting `main()`!).

**Comment by v1993** [comment]
@qwertychouskie By the way, can you make smaller pull requests, please? AFAIK, for now you commit everything into one branch. That would be easier to review, test and merge.

In this case you can replace all `using xx = struct {…}` with structs with `struct xx {…}`. This should be pretty easy.

**Comment by qwertychouskie** [comment]
Fixed in https://github.com/cubosphere/cubosphere-code/commit/dad49a0b6a19d5fa061099781912d486e7297803.  @cddepppp256 You should be able to use GCC now.
